web-1  | [SQL: INSERT INTO schedule (technician_id, start_time, end_time, description, location_id, created_at, time_off) VALUES (%(technician_id)s, %(start_time)s, %(end_time)s, %(description)s, %(location_id)s, %(created_at)s, %(time_off)s) RETURNING schedule.id]
web-1  | [parameters: {'technician_id': 12, 'start_time': datetime.datetime(2025, 2, 17, 9, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'end_time': datetime.datetime(2025, 2, 17, 17, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'description': '', 'location_id': 7, 'created_at': datetime.datetime(2025, 7, 13, 21, 28, 16, 568353, tzinfo=<UTC>), 'time_off': False}]
web-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
web-1  | ERROR:app:Error processing schedule: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
web-1  | (psycopg2.errors.ForeignKeyViolation) insert or update on table "schedule" violates foreign key constraint "schedule_technician_id_fkey"
web-1  | DETAIL:  Key (technician_id)=(12) is not present in table "users".
web-1  |
web-1  | [SQL: INSERT INTO schedule (technician_id, start_time, end_time, description, location_id, created_at, time_off) VALUES (%(technician_id)s, %(start_time)s, %(end_time)s, %(description)s, %(location_id)s, %(created_at)s, %(time_off)s) RETURNING schedule.id]
web-1  | [parameters: {'technician_id': 12, 'start_time': datetime.datetime(2025, 2, 17, 9, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'end_time': datetime.datetime(2025, 2, 17, 17, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'description': '', 'location_id': 7, 'created_at': datetime.datetime(2025, 7, 13, 21, 28, 16, 568353, tzinfo=<UTC>), 'time_off': False}]
web-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
web-1  | ERROR:app:Error processing schedule: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
web-1  | (psycopg2.errors.ForeignKeyViolation) insert or update on table "schedule" violates foreign key constraint "schedule_technician_id_fkey"
web-1  | DETAIL:  Key (technician_id)=(12) is not present in table "users".
web-1  |
web-1  | [SQL: INSERT INTO schedule (technician_id, start_time, end_time, description, location_id, created_at, time_off) VALUES (%(technician_id)s, %(start_time)s, %(end_time)s, %(description)s, %(location_id)s, %(created_at)s, %(time_off)s) RETURNING schedule.id]
web-1  | [parameters: {'technician_id': 12, 'start_time': datetime.datetime(2025, 2, 17, 9, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'end_time': datetime.datetime(2025, 2, 17, 17, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'description': '', 'location_id': 7, 'created_at': datetime.datetime(2025, 7, 13, 21, 28, 16, 568353, tzinfo=<UTC>), 'time_off': False}]
web-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
web-1  | ERROR:app:Error processing schedule: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
web-1  | (psycopg2.errors.ForeignKeyViolation) insert or update on table "schedule" violates foreign key constraint "schedule_technician_id_fkey"
web-1  | DETAIL:  Key (technician_id)=(12) is not present in table "users".
web-1  |
web-1  | [SQL: INSERT INTO schedule (technician_id, start_time, end_time, description, location_id, created_at, time_off) VALUES (%(technician_id)s, %(start_time)s, %(end_time)s, %(description)s, %(location_id)s, %(created_at)s, %(time_off)s) RETURNING schedule.id]
web-1  | [parameters: {'technician_id': 12, 'start_time': datetime.datetime(2025, 2, 17, 9, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'end_time': datetime.datetime(2025, 2, 17, 17, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'description': '', 'location_id': 7, 'created_at': datetime.datetime(2025, 7, 13, 21, 28, 16, 568353, tzinfo=<UTC>), 'time_off': False}]
web-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
web-1  | ERROR:app:Error processing schedule: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
web-1  | (psycopg2.errors.ForeignKeyViolation) insert or update on table "schedule" violates foreign key constraint "schedule_technician_id_fkey"
web-1  | DETAIL:  Key (technician_id)=(12) is not present in table "users".
web-1  |
web-1  | [SQL: INSERT INTO schedule (technician_id, start_time, end_time, description, location_id, created_at, time_off) VALUES (%(technician_id)s, %(start_time)s, %(end_time)s, %(description)s, %(location_id)s, %(created_at)s, %(time_off)s) RETURNING schedule.id]
web-1  | [parameters: {'technician_id': 12, 'start_time': datetime.datetime(2025, 2, 17, 9, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'end_time': datetime.datetime(2025, 2, 17, 17, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'description': '', 'location_id': 7, 'created_at': datetime.datetime(2025, 7, 13, 21, 28, 16, 568353, tzinfo=<UTC>), 'time_off': False}]
web-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
web-1  | ERROR:app:Error processing schedule: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
web-1  | (psycopg2.errors.ForeignKeyViolation) insert or update on table "schedule" violates foreign key constraint "schedule_technician_id_fkey"
web-1  | DETAIL:  Key (technician_id)=(12) is not present in table "users".
web-1  |
web-1  | [SQL: INSERT INTO schedule (technician_id, start_time, end_time, description, location_id, created_at, time_off) VALUES (%(technician_id)s, %(start_time)s, %(end_time)s, %(description)s, %(location_id)s, %(created_at)s, %(time_off)s) RETURNING schedule.id]
web-1  | [parameters: {'technician_id': 12, 'start_time': datetime.datetime(2025, 2, 17, 9, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'end_time': datetime.datetime(2025, 2, 17, 17, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'description': '', 'location_id': 7, 'created_at': datetime.datetime(2025, 7, 13, 21, 28, 16, 568353, tzinfo=<UTC>), 'time_off': False}]
web-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
web-1  | ERROR:app:Error processing schedule: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
web-1  | (psycopg2.errors.ForeignKeyViolation) insert or update on table "schedule" violates foreign key constraint "schedule_technician_id_fkey"
web-1  | DETAIL:  Key (technician_id)=(12) is not present in table "users".
web-1  |
web-1  | [SQL: INSERT INTO schedule (technician_id, start_time, end_time, description, location_id, created_at, time_off) VALUES (%(technician_id)s, %(start_time)s, %(end_time)s, %(description)s, %(location_id)s, %(created_at)s, %(time_off)s) RETURNING schedule.id]
web-1  | [parameters: {'technician_id': 12, 'start_time': datetime.datetime(2025, 2, 17, 9, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'end_time': datetime.datetime(2025, 2, 17, 17, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'description': '', 'location_id': 7, 'created_at': datetime.datetime(2025, 7, 13, 21, 28, 16, 568353, tzinfo=<UTC>), 'time_off': False}]
web-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
web-1  | ERROR:app:Error processing schedule: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
web-1  | (psycopg2.errors.ForeignKeyViolation) insert or update on table "schedule" violates foreign key constraint "schedule_technician_id_fkey"
web-1  | DETAIL:  Key (technician_id)=(12) is not present in table "users".
web-1  |
web-1  | [SQL: INSERT INTO schedule (technician_id, start_time, end_time, description, location_id, created_at, time_off) VALUES (%(technician_id)s, %(start_time)s, %(end_time)s, %(description)s, %(location_id)s, %(created_at)s, %(time_off)s) RETURNING schedule.id]
web-1  | [parameters: {'technician_id': 12, 'start_time': datetime.datetime(2025, 2, 17, 9, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'end_time': datetime.datetime(2025, 2, 17, 17, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'description': '', 'location_id': 7, 'created_at': datetime.datetime(2025, 7, 13, 21, 28, 16, 568353, tzinfo=<UTC>), 'time_off': False}]
web-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
web-1  | ERROR:app:Error processing schedule: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
web-1  | (psycopg2.errors.ForeignKeyViolation) insert or update on table "schedule" violates foreign key constraint "schedule_technician_id_fkey"
web-1  | DETAIL:  Key (technician_id)=(12) is not present in table "users".
web-1  |
web-1  | [SQL: INSERT INTO schedule (technician_id, start_time, end_time, description, location_id, created_at, time_off) VALUES (%(technician_id)s, %(start_time)s, %(end_time)s, %(description)s, %(location_id)s, %(created_at)s, %(time_off)s) RETURNING schedule.id]
web-1  | [parameters: {'technician_id': 12, 'start_time': datetime.datetime(2025, 2, 17, 9, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'end_time': datetime.datetime(2025, 2, 17, 17, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'description': '', 'location_id': 7, 'created_at': datetime.datetime(2025, 7, 13, 21, 28, 16, 568353, tzinfo=<UTC>), 'time_off': False}]
web-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
web-1  | ERROR:app:Error processing schedule: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
web-1  | (psycopg2.errors.ForeignKeyViolation) insert or update on table "schedule" violates foreign key constraint "schedule_technician_id_fkey"
web-1  | DETAIL:  Key (technician_id)=(12) is not present in table "users".
web-1  |
web-1  | [SQL: INSERT INTO schedule (technician_id, start_time, end_time, description, location_id, created_at, time_off) VALUES (%(technician_id)s, %(start_time)s, %(end_time)s, %(description)s, %(location_id)s, %(created_at)s, %(time_off)s) RETURNING schedule.id]
web-1  | [parameters: {'technician_id': 12, 'start_time': datetime.datetime(2025, 2, 17, 9, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'end_time': datetime.datetime(2025, 2, 17, 17, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'description': '', 'location_id': 7, 'created_at': datetime.datetime(2025, 7, 13, 21, 28, 16, 568353, tzinfo=<UTC>), 'time_off': False}]
web-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
web-1  | ERROR:app:Error processing schedule: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
web-1  | (psycopg2.errors.ForeignKeyViolation) insert or update on table "schedule" violates foreign key constraint "schedule_technician_id_fkey"
web-1  | DETAIL:  Key (technician_id)=(12) is not present in table "users".
web-1  |
web-1  | [SQL: INSERT INTO schedule (technician_id, start_time, end_time, description, location_id, created_at, time_off) VALUES (%(technician_id)s, %(start_time)s, %(end_time)s, %(description)s, %(location_id)s, %(created_at)s, %(time_off)s) RETURNING schedule.id]
web-1  | [parameters: {'technician_id': 12, 'start_time': datetime.datetime(2025, 2, 17, 9, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'end_time': datetime.datetime(2025, 2, 17, 17, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'description': '', 'location_id': 7, 'created_at': datetime.datetime(2025, 7, 13, 21, 28, 16, 568353, tzinfo=<UTC>), 'time_off': False}]
web-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
web-1  | ERROR:app:Error processing schedule: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
web-1  | (psycopg2.errors.ForeignKeyViolation) insert or update on table "schedule" violates foreign key constraint "schedule_technician_id_fkey"
web-1  | DETAIL:  Key (technician_id)=(12) is not present in table "users".
web-1  |
web-1  | [SQL: INSERT INTO schedule (technician_id, start_time, end_time, description, location_id, created_at, time_off) VALUES (%(technician_id)s, %(start_time)s, %(end_time)s, %(description)s, %(location_id)s, %(created_at)s, %(time_off)s) RETURNING schedule.id]
web-1  | [parameters: {'technician_id': 12, 'start_time': datetime.datetime(2025, 2, 17, 9, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'end_time': datetime.datetime(2025, 2, 17, 17, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'description': '', 'location_id': 7, 'created_at': datetime.datetime(2025, 7, 13, 21, 28, 16, 568353, tzinfo=<UTC>), 'time_off': False}]
web-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
web-1  | ERROR:app:Error processing schedule: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
web-1  | (psycopg2.errors.ForeignKeyViolation) insert or update on table "schedule" violates foreign key constraint "schedule_technician_id_fkey"
web-1  | DETAIL:  Key (technician_id)=(12) is not present in table "users".
web-1  |
web-1  | [SQL: INSERT INTO schedule (technician_id, start_time, end_time, description, location_id, created_at, time_off) VALUES (%(technician_id)s, %(start_time)s, %(end_time)s, %(description)s, %(location_id)s, %(created_at)s, %(time_off)s) RETURNING schedule.id]
web-1  | [parameters: {'technician_id': 12, 'start_time': datetime.datetime(2025, 2, 17, 9, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'end_time': datetime.datetime(2025, 2, 17, 17, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'description': '', 'location_id': 7, 'created_at': datetime.datetime(2025, 7, 13, 21, 28, 16, 568353, tzinfo=<UTC>), 'time_off': False}]
web-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
web-1  | ERROR:app:Error in backup restoration: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
web-1  | (psycopg2.errors.ForeignKeyViolation) insert or update on table "schedule" violates foreign key constraint "schedule_technician_id_fkey"
web-1  | DETAIL:  Key (technician_id)=(12) is not present in table "users".
web-1  |
web-1  | [SQL: INSERT INTO schedule (technician_id, start_time, end_time, description, location_id, created_at, time_off) VALUES (%(technician_id)s, %(start_time)s, %(end_time)s, %(description)s, %(location_id)s, %(created_at)s, %(time_off)s) RETURNING schedule.id]
web-1  | [parameters: {'technician_id': 12, 'start_time': datetime.datetime(2025, 2, 17, 9, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'end_time': datetime.datetime(2025, 2, 17, 17, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'description': '', 'location_id': 7, 'created_at': datetime.datetime(2025, 7, 13, 21, 28, 16, 568353, tzinfo=<UTC>), 'time_off': False}]
web-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
web-1  | ERROR:app:Unexpected error in restore_backup: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
web-1  | (psycopg2.errors.ForeignKeyViolation) insert or update on table "schedule" violates foreign key constraint "schedule_technician_id_fkey"
web-1  | DETAIL:  Key (technician_id)=(12) is not present in table "users".
web-1  |
web-1  | [SQL: INSERT INTO schedule (technician_id, start_time, end_time, description, location_id, created_at, time_off) VALUES (%(technician_id)s, %(start_time)s, %(end_time)s, %(description)s, %(location_id)s, %(created_at)s, %(time_off)s) RETURNING schedule.id]
web-1  | [parameters: {'technician_id': 12, 'start_time': datetime.datetime(2025, 2, 17, 9, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'end_time': datetime.datetime(2025, 2, 17, 17, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), 'description': '', 'location_id': 7, 'created_at': datetime.datetime(2025, 7, 13, 21, 28, 16, 568353, tzinfo=<UTC>), 'time_off': False}]
web-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
web-1  | DEBUG:app:Current time (UTC): 2025-07-13 21:28:17.019990+00:00
web-1  | DEBUG:app:Active users query SQL: SELECT "user".id AS user_id, "user".username AS user_username, "user".email AS user_email, "user".password_hash AS user_password_hash, "user".is_admin AS user_is_admin, "user".color AS user_color, "user".timezone AS user_timezone, "user".theme_preference AS user_theme_preference, "user".profile_picture AS user_profile_picture, schedule.id AS schedule_id, schedule.technician_id AS schedule_technician_id, schedule.start_time AS schedule_start_time, schedule.end_time AS schedule_end_time, schedule.description AS schedule_description, schedule.location_id AS schedule_location_id, schedule.created_at AS schedule_created_at, schedule.time_off AS schedule_time_off, location.id AS location_id, location.name AS location_name, location.description AS location_description, location.active AS location_active, location.created_at AS location_created_at, location.updated_at AS location_updated_at
web-1  | FROM "user" JOIN schedule ON "user".id = schedule.technician_id LEFT OUTER JOIN location ON schedule.location_id = location.id
web-1  | WHERE schedule.start_time <= %(start_time_1)s AND schedule.end_time > %(end_time_1)s AND NOT schedule.time_off
web-1  | DEBUG:app:Found 0 active schedules
web-1  | DEBUG:app:Returning 0 active users